version: "1"
services:
  - type: web
    name: speech-to-text
    runtime: node
    buildCommand: bun install && bun run build
    startCommand: bun run start
    buildFilter:
      paths:
        - "**/*"
      ignoredPaths:
        - ".git/**"
        - "node_modules/**"
    envVars:
      - key: LEMONFOX_API_KEY
        sync: false
      - key: BUN_VERSION
        value: "1.0.30"
    autoDeploy: true
    plan: free
    healthCheckPath: / # Adding health check for the web service 