version: "1"
services:
  - type: web
    name: speech-to-text
    runtime: node
    buildCommand: |
      corepack enable
      yarn install
      yarn build
    startCommand: PORT=$PORT yarn start
    buildFilter:
      paths:
        - "**/*"
      ignoredPaths:
        - ".git/**"
        - "node_modules/**"
    envVars:
      - key: LEMONFOX_API_KEY
        sync: false
    autoDeploy: true
    plan: free
    healthCheckPath: / # Adding health check for the web service 