version: "1"
services:
  - type: web
    name: speech-to-text
    runtime: node
    buildCommand: curl -fsSL https://bun.sh/install | bash && ~/.bun/bin/bun install && ~/.bun/bin/bun run build
    startCommand: ~/.bun/bin/bun run start
    buildFilter:
      paths:
        - "**/*"
      ignoredPaths:
        - ".git/**"
        - "node_modules/**"
    envVars:
      - key: LEMONFOX_API_KEY
        sync: false
      - key: NODE_VERSION
        value: "20.11.1"
      - key: BUN_VERSION
        value: "1.0.30"
    autoDeploy: true
    plan: free
    healthCheckPath: / # Adding health check for the web service 