version: "1"
services:
  - type: web
    name: speech-to-text
    runtime: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    buildFilter:
      paths:
        - "**/*"
      ignoredPaths:
        - ".git/**"
        - "node_modules/**"
    envVars:
      - key: LEMONFOX_API_KEY
        sync: false
      - key: NODE_VERSION
        value: "20.11.1"
    autoDeploy: true
    plan: free
    healthCheckPath: / # Adding health check for the web service 