version: "1"
services:
  - type: web
    name: speech-to-text
    runtime: node
    buildCommand: |
      node .yarn/releases/yarn-4.6.0.cjs install
      node .yarn/releases/yarn-4.6.0.cjs build
    startCommand: node .yarn/releases/yarn-4.6.0.cjs start
    buildFilter:
      paths:
        - "**/*"
      ignoredPaths:
        - ".git/**"
        - "node_modules/**"
    envVars:
      - key: LEMONFOX_API_KEY
        sync: false
    autoDeploy: true
    plan: free
    healthCheckPath: / # Adding health check for the web service 